name: Phase 4 Feature
description: Create a Phase 4 distributed state & events feature
title: '[Phase 4] '
labels: ['phase-4', 'feature']
assignees:
  - Copilot
body:
  - type: markdown
    attributes:
      value: |
        ## Phase 4: Distributed State & Events
        This template is for Phase 4 features related to event-driven architecture, message queues, event sourcing, and service contracts.

  - type: input
    id: feature-name
    attributes:
      label: Feature Name
      description: Brief name for the feature
      placeholder: e.g., Event Sourcing & GraphQL
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Detailed description of the feature
      placeholder: Describe what this feature will accomplish...
    validations:
      required: true

  - type: textarea
    id: technical-requirements
    attributes:
      label: Technical Requirements
      description: Technical specifications and implementation details
      placeholder: |
        ### Files to Create/Modify
        - `packages/...`

        ### Implementation Details
        - ...
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria / Definition of Done
      description: Specific criteria that must be met for completion
      placeholder: |
        - [ ] Core functionality implemented
        - [ ] Tests passing
        - [ ] Documentation updated
        - [ ] Performance requirements met
    validations:
      required: true

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: Prerequisites and related issues
      placeholder: |
        ### Prerequisites
        - Issue #XX: ...

        ### Related Issues
        - Issue #XX: ...
    validations:
      required: false

  - type: textarea
    id: success-metrics
    attributes:
      label: Success Metrics
      description: How will success be measured?
      placeholder: |
        ### Performance Targets
        - Latency: <Xms p95
        - Throughput: >X requests/second

        ### Quality Goals
        - Test coverage: >X%
        - Documentation completeness: 100%
    validations:
      required: false
