name: CI
on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: app
        ports: ['5432:5432']
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
      redis:
        image: redis:7-alpine
        ports: ['6379:6379']
        options: >-
          --health-cmd="redis-cli ping || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/app
      REDIS_URL: redis://localhost:6379
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: testsecret
      NODE_ENV: test
      CI: true

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci --include-workspace-root --workspaces

      - name: Generate Prisma Client
        run: npm run generate --workspace=apps/web

      - name: Apply DB migrations
        run: npm run migrate:deploy --workspace=apps/web

      - name: Seed DB
        run: npm run seed --workspace=apps/web

      - name: Build gateway package first
        run: npm run build --workspace=packages/gateway

      - name: Run ESLint
        run: npm run lint

      - name: Check Prettier formatting
        run: npm run format:check

      - name: Type check
        run: npm run type-check

      - name: Build application
        run: npm run build --workspace=apps/web
        env:
          # LiteLLM configuration for build
          LITELLM_BASE_URL: http://localhost:4000
          LITELLM_TIMEOUT: 30000

      - name: Install Playwright browsers
        run: npx playwright install --with-deps
        working-directory: tests/e2e

      - name: Unit tests
        run: npm run test --workspace=tests/unit

      - name: E2E tests (Playwright)
        env:
          BASE_URL: http://localhost:3000
          # LiteLLM test configuration - will use mock gateway automatically
          LITELLM_BASE_URL: http://localhost:4000
          LITELLM_TIMEOUT: 5000
        run: npm run e2e --workspace=tests/e2e

      - name: Generate Enhanced SBOM (CycloneDX 1.6)
        if: always()
        run: |
          # Generate comprehensive SBOM with CycloneDX 1.6 specification
          npx @cyclonedx/cyclonedx-npm \
            --output-file sbom.json \
            --spec-version 1.6 \
            
            
            --output-reproducible || true

          # Generate SPDX format SBOM for compatibility
          npx @cyclonedx/cyclonedx-npm \
            --output-file sbom.spdx.json \
            --output-format JSON \
            --spec-version 1.6 \
            
            --include-optional || true

      - name: Generate Build Provenance Data
        if: always()
        run: |
          # Create build information for provenance
          echo "Creating build provenance data..."
          cat > build-info.json << EOF
          {
            "buildTimestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
            "gitCommit": "${{ github.sha }}",
            "gitRef": "${{ github.ref }}",
            "repository": "${{ github.repository }}",
            "runId": "${{ github.run_id }}",
            "runNumber": "${{ github.run_number }}",
            "nodeVersion": "$(node --version)",
            "npmVersion": "$(npm --version)",
            "runner": {
              "os": "${{ runner.os }}",
              "arch": "${{ runner.arch }}",
              "name": "${{ runner.name }}"
            }
          }
          EOF

      - name: Create Security Evidence Bundle
        if: always()
        run: |
          # Create a comprehensive security evidence bundle
          mkdir -p security-evidence

          # Copy SBOMs
          cp sbom.json security-evidence/ 2>/dev/null || echo "CycloneDX SBOM not found"
          cp sbom.spdx.json security-evidence/ 2>/dev/null || echo "SPDX SBOM not found"

          # Copy build info
          cp build-info.json security-evidence/ 2>/dev/null || echo "Build info not found"

          # Create evidence manifest
          cat > security-evidence/manifest.json << EOF
          {
            "evidenceType": "security-bundle",
            "generatedAt": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
            "buildId": "${{ github.run_id }}",
            "commitSha": "${{ github.sha }}",
            "contents": {
              "sbom": {
                "cycloneDx": "sbom.json",
                "spdx": "sbom.spdx.json"
              },
              "buildInfo": "build-info.json",
              "compliance": {
                "asvs": "planned",
                "slsa": "in-progress",
                "aiAct": "planned"
              }
            }
          }
          EOF

          # List all evidence files
          echo "Security Evidence Bundle Contents:"
          ls -la security-evidence/

      - name: Upload artifacts (reports, traces, logs, sbom, evidence)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: |
            tests/e2e/playwright-report/
            tests/e2e/test-results/
            sbom.json
            sbom.spdx.json
            build-info.json
            security-evidence/
            **/junit*.xml
            **/logs/**
